#!/usr/bin/env bash

cd /autograder/source

# Set up autograder files
cp /autograder/submission/* .


pip3 install --user click
pip3 install --user PyYAML
pip3 install --user gradescope-utils>=0.2.6
pip3 install --user lizard

python3 submission_checker.py
RC=$?

if [ "$RC" -eq 1 ]; then
    # Run the autograder code
    bash ./MAKE-REFERENCE.sh
    bash ./grade.sh
fi
